[package]
name = "cairn-exec"
description = "Catalog, query planner and executor for cairn"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
cairn-storage = { path = "../storage" }
cairn-sql = { path = "../sql" }

[lints]
workspace = true
