CREATE TABLE t (id INTEGER PRIMARY KEY, r REAL NOT NULL, s TEXT UNIQUE, b BOOLEAN);
CREATE TABLE IF NOT EXISTS t (x INTEGER);
INSERT INTO t VALUES (1, 2.5, 'a', TRUE);
SELECT * FROM t;
SELECT id, r, s, b FROM t WHERE b;
