CREATE TABLE t (a INTEGER, b TEXT);
INSERT INTO t VALUES (1);
INSERT INTO t (a) VALUES (1, 'x');
INSERT INTO t (a, zz) VALUES (1, 2);
INSERT INTO t (a, a) VALUES (1, 2);
INSERT INTO t VALUES (a, 'x');
INSERT INTO nope VALUES (1);
INSERT INTO t VALUES (1, 'ok'), (2);
SELECT COUNT(*) AS n FROM t;
