CREATE TABLE t (a INTEGER NOT NULL, b TEXT NOT NULL, c TEXT);
INSERT INTO t VALUES (1, 'x', NULL);
INSERT INTO t VALUES (NULL, 'x', 'c');
INSERT INTO t (a) VALUES (2);
INSERT INTO t (a, b) VALUES (3, 'y'), (4, NULL);
SELECT a, b, c FROM t;
