CREATE TABLE t (code TEXT PRIMARY KEY, n INTEGER);
INSERT INTO t VALUES ('b', 1), ('a', 2);
INSERT INTO t VALUES ('a', 3);
INSERT INTO t VALUES (NULL, 4);
SELECT code, n FROM t;
EXPLAIN SELECT n FROM t WHERE code = 'a';
