SELECT TRUE AND NULL AS a, FALSE AND NULL AS b, TRUE OR NULL AS c, FALSE OR NULL AS d, NOT NULL AS e;
SELECT NULL IS NULL AS a, NULL IS NOT NULL AS b, 1 IS NULL AS c, NULL = NULL AS d, NULL <> 1 AS e;
SELECT NOT (NULL AND FALSE) AS a, (NULL OR TRUE) AS b, 1 = 1 AND 2 > 1 AS c;
