SELECT 1 / 0;
SELECT 1 % 0;
SELECT 1.5 / 0;
SELECT 1 / 0.0;
CREATE TABLE t (a INTEGER);
INSERT INTO t VALUES (1), (0);
SELECT a FROM t WHERE 10 / a > 1;
SELECT a, 10 / a AS q FROM t WHERE a <> 0;
SELECT 1 / NULL AS n;
