CREATE TABLE t (id INTEGER PRIMARY KEY, n INTEGER);
INSERT INTO t VALUES (1, 5), (2, 15), (3, NULL);
SELECT id, CASE WHEN n < 10 THEN 'small' WHEN n < 100 THEN 'big' END AS size FROM t;
SELECT id, CASE WHEN n > 0 THEN 'pos' ELSE 'other' END AS sign FROM t;
SELECT CASE WHEN n > 10 THEN 1 ELSE 0.5 END AS v FROM t;
SELECT CASE WHEN TRUE THEN 'a' WHEN TRUE THEN 'b' END AS first;
SELECT CASE WHEN 1 THEN 'x' END;
SELECT CASE WHEN TRUE THEN 1 ELSE 'x' END;
