SELECT LOWER('HeLLo') AS a, UPPER('straße') AS b, LENGTH('héllo') AS c, LENGTH('') AS d;
SELECT ABS(-5) AS a, ABS(2.5) AS b, ABS(-0.5) AS c, ABS(NULL) AS d;
SELECT COALESCE(NULL, NULL, 3) AS a, COALESCE(NULL, 'x') AS b, COALESCE(1, 2.5) AS c, COALESCE(NULL) AS d;
SELECT LOWER(NULL) AS a, UPPER(NULL) AS b, LENGTH(NULL) AS c;
CREATE TABLE t (s TEXT);
INSERT INTO t VALUES ('Mixed Case'), (NULL);
SELECT UPPER(s), LENGTH(s) FROM t;
