SELECT nope(1);
SELECT LOWER('a', 'b');
SELECT COALESCE();
SELECT LOWER(DISTINCT 'a');
SELECT SUM(*);
CREATE TABLE t (a INTEGER);
SELECT a FROM t WHERE COUNT(*) > 0;
SELECT LOWER(1);
SELECT SUM('x') FROM t;
