CREATE TABLE t (g TEXT, v INTEGER);
INSERT INTO t VALUES ('a', 1), ('a', 2), ('b', 10), ('c', NULL);
SELECT g, SUM(v) AS s FROM t GROUP BY g HAVING SUM(v) > 2;
SELECT g FROM t GROUP BY g HAVING COUNT(*) = 1;
SELECT COUNT(*) AS n FROM t HAVING COUNT(*) > 100;
SELECT COUNT(*) AS n FROM t HAVING COUNT(*) > 1;
SELECT g FROM t GROUP BY g HAVING g <> 'a';
