CREATE TABLE t (g TEXT, v INTEGER);
SELECT g, v FROM t GROUP BY g;
SELECT v, COUNT(*) FROM t;
SELECT SUM(COUNT(v)) FROM t;
SELECT g FROM t GROUP BY SUM(v);
SELECT g FROM t GROUP BY g ORDER BY v;
SELECT g FROM t GROUP BY g HAVING v > 1;
SELECT g FROM t GROUP BY g HAVING SUM(v);
