CREATE TABLE t (a INTEGER, b TEXT);
INSERT INTO t VALUES (2, 'x'), (1, 'y'), (2, 'x'), (NULL, 'z'), (NULL, 'z'), (1, 'x');
SELECT DISTINCT a FROM t;
SELECT DISTINCT a, b FROM t;
SELECT DISTINCT a FROM t ORDER BY a;
SELECT COUNT(DISTINCT a) AS n FROM t;
