CREATE TABLE t (id INTEGER PRIMARY KEY, a INTEGER);
INSERT INTO t VALUES (1, 30), (2, 10), (3, 20);
SELECT id, a * -1 AS neg FROM t ORDER BY neg;
SELECT id, a FROM t ORDER BY 2 DESC;
SELECT id FROM t ORDER BY a;
SELECT id FROM t ORDER BY 3;
SELECT DISTINCT id FROM t ORDER BY a;
SELECT DISTINCT a AS x FROM t ORDER BY x DESC;
