CREATE TABLE t (id INTEGER PRIMARY KEY);
INSERT INTO t VALUES (1), (2), (3), (4), (5);
SELECT id FROM t LIMIT 2;
SELECT id FROM t LIMIT 2 OFFSET 3;
SELECT id FROM t LIMIT 10 OFFSET 4;
SELECT id FROM t LIMIT 3 OFFSET 10;
SELECT id FROM t LIMIT 0;
SELECT id FROM t ORDER BY id DESC LIMIT 2 OFFSET 1;
