CREATE TABLE t (id INTEGER PRIMARY KEY, v TEXT);
INSERT INTO t VALUES (1, 'a'), (5, 'b'), (9, 'c');
EXPLAIN SELECT v FROM t WHERE id = 5;
SELECT v FROM t WHERE id = 5;
EXPLAIN SELECT v FROM t WHERE id > 1 AND id <= 9;
SELECT v FROM t WHERE id > 1 AND id <= 9;
EXPLAIN SELECT v FROM t WHERE id BETWEEN 2 AND 6;
explain SELECT * FROM t WHERE id < 0 LIMIT 1;
