CREATE TABLE t (id INTEGER PRIMARY KEY, a INTEGER, b TEXT);
CREATE INDEX t_a ON t (a);
EXPLAIN SELECT id FROM t WHERE b = 'x';
EXPLAIN SELECT id FROM t WHERE a + 1 = 2;
EXPLAIN SELECT id FROM t WHERE a = 1 OR a = 2;
EXPLAIN SELECT id FROM t WHERE a = id;
EXPLAIN SELECT id FROM t WHERE a = 1.5;
EXPLAIN SELECT id FROM t;
